Remove unused variable
as per title

```
workspace/ros2/ros2_control_ws/src/ros-controls/ros2_controllers/joint_state_broadcaster/test/test_joint_state_broadcaster.cpp:326:16: error: unused variable ‘NUM_IFS’ [-Werror=unused-variable]
  326 |   const size_t NUM_IFS = IF_NAMES.size();
```