joint_state_trajectory: Fix linking of target `test_load_joint_trajectory_controller`
Fixes "No such file or directory" error:
`joint_trajectory_controller.hpp:27:10: fatal error: control_toolbox/pid.hpp: ...`

It needs `control_toolbox`, but depends on `joint_trajectory_controller` anyway. Hence
the single-target linking, just as it is done for all other test-targets here as well.

fixup for 1fd8bc37f284098aed39d4e6bd324a8528a72ad4